/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:35eb80fb-2336-4e5e-b938-02d4ff5b1760",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_i5ejRmnQN",
    "aws_user_pools_web_client_id": "80jc1gp6iljpo0cq0s5qelfb5",
    "oauth": {}
};


export default awsmobile;
